name: "🟢 Story (Layer 1)"
description: "A specific feature requirement or user-facing capability (Roadmap Item)."
title: "[STORY] "
labels: ["0. layer: story"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story
        Describe a feature from the user's perspective: **"As a [role], I want [feature], so that [benefit]."**

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      placeholder: |
        As a developer using GlaDOS,
        I want the parser to handle lists
        So that I can work with list data structures easily.
    validations:
      required: true

# Commented out because feel useless.
# Not removed because Epi might like it.
  # - type: textarea
  #   id: acceptance_criteria
  #   attributes:
  #     label: Definition of Done (Acceptance Criteria)
  #     description: What must be true for this Story to be complete?
  #     value: |
  #       - [ ] Functional implementation complete
  #       - [ ] Unit tests written and passing
  #       - [ ] Integration tests added
  #       - [ ] Documentation updated (user manual + code comments)
  #       - [ ] No regressions in existing functionality
  #   validations:
  #     required: true

  - type: input
    id: parent_epic
    attributes:
      label: Parent Epic
      description: Link the Epic this Story belongs to
      placeholder: "#12"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Estimated Difficulty
      options:
        - "1. difficulty: easy"
        - "1. difficulty: medium"
        - "1. difficulty: hard"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "2. priority: critical"
        - "2. priority: high"
        - "2. priority: medium"
        - "2. priority: low"
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or constraints
      placeholder: |
        - Must handle recursive calls without stack overflow
        - Consider tail-call optimization
        - Need to maintain closure environments

  - type: textarea
    id: child_tasks
    attributes:
      label: Child Tasks
      description: Specific implementation tasks (will be created as separate issues)
      value: |
        - [ ] #
        - [ ] #

  - type: textarea
    id: relationships
    attributes:
      label: Relationships
      description: Dependencies and blocking relationships.
      value: |
        **Blocked by:**
        - [ ] #

        **Blocking:**
        - [ ] #

  - type: input
    id: sprint
    attributes:
      label: Target Sprint
      description: Target sprint or date for this Story
      placeholder: "Sprint 2"
