name: "Addon: Repro Snippets"
description: "Add-on: Minimal reproducible code or commands"
body:
  - type: "markdown"
    attributes:
      value: |
        # Minimal Repro Add-on

        Provide a small, self-contained example to reproduce the issue.
  - type: "textarea"
    id: "repro_snippet"
    attributes:
      label: "Minimal Repro (copy-paste runnable snippet)"
      description: "Paste commands, code, curl requests, or steps that reproduce the issue."
      placeholder: |
        ```bash
        # e.g., commands to reproduce
        npm install
        npm run dev
        # Navigate to http://localhost:3000 and observe error
        ```
      render: "bash"
    validations:
      required: false
  - type: "input"
    id: "repro_link"
    attributes:
      label: "Link to reproduction repo"
      description: "If you have a minimal repo that reproduces the issue, link it here."
      placeholder: "https://github.com/username/reproduction-repo"
    validations:
      required: false
