name: " Regression"
description: "Report something that used to work but no longer does"
labels: ["3.type: regression"]
body:
  - type: "markdown"
    attributes:
      value: |
        # Regression

        A regression means something that previously worked is now broken.
  - type: "input"
    id: "working_version"
    attributes:
      label: "Previously Working Version"
      description: "Which version or commit did this last work on?"
      placeholder: "e.g., v1.2.0, commit abc123"
    validations:
      required: true
  - type: "textarea"
    id: "reproduction_steps"
    attributes:
      label: "Steps to Reproduce"
      description: "Provide numbered steps to reproduce the issue."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: "textarea"
    id: "current_behavior"
    attributes:
      label: "Current Behavior"
      description: "What is happening now?"
    validations:
      required: true
  - type: "textarea"
    id: "expected_behavior"
    attributes:
      label: "Expected Behavior"
      description: "What should happen instead?"
    validations:
      required: true
  - type: "input"
    id: "related_changes"
    attributes:
      label: "Related Changes"
      description: "Any PRs, commits, or merges that might have caused it?"
      placeholder: "PR #123, commit abc123"
    validations:
      required: false
  - type: "textarea"
    id: "notes"
    attributes:
      label: "Notes / Context"
      description: "Any logs, environment info, or relevant discussions."
    validations:
      required: false
