name: "Task"
description: "Describe a task or implementation detail"
labels: ["task"]
body:
  - type: "markdown"
    attributes:
      value: |
        # Task / Implementation

        Break down work into actionable tasks.
  - type: "textarea"
    id: "task_description"
    attributes:
      label: "Description"
      description: "Short explanation of what needs to be done."
    validations:
      required: true
  - type: "textarea"
    id: "technical_details"
    attributes:
      label: "Technical Details"
      description: "Add any relevant technical notes, hints, files to change, or commands."
    validations:
      required: false
  - type: "checkboxes"
    id: "acceptance_criteria"
    attributes:
      label: "Acceptance Criteria"
      description: "What needs to be done for this task to be complete?"
      options:
        - label: "Functionality works as expected"
          required: false
        - label: "Unit tests added"
          required: false
        - label: "Documentation updated"
          required: false
        - label: "Code reviewed"
          required: false
  - type: "input"
    id: "related"
    attributes:
      label: "Related Issues / PRs"
      description: "List related issue numbers or PR links."
      placeholder: "Related to #123, Follows #456"
    validations:
      required: false
